using System.IO;
using PdfSharp;
using PdfSharp.Drawing;
using PdfSharp.Fonts;
using PdfSharp.Pdf;

namespace NwdViewer.Desktop.Services;

/// <summary>
/// Generates single-page PDF reports from the viewer's screenshot. Landscape US Letter.
/// </summary>
public static class PdfExport
{
    static PdfExport()
    {
        // PDFsharp 6.x on .NET Core requires an explicit font resolver.
        if (GlobalFontSettings.FontResolver is null)
            GlobalFontSettings.FontResolver = new WindowsFontResolver();
    }


    private const double MarginPt   = 36;   // 0.5 inch
    private const double FooterPt   = 30;
    private const double HeaderPt   = 26;

    public static void WriteSinglePage(string path, byte[] pngBytes, string modelTitle)
    {
        using var pdf = new PdfDocument();
        pdf.Info.Title = "3D Model Viewer — " + modelTitle;
        pdf.Info.Creator = "NwdViewer";

        var page = pdf.AddPage();
        page.Orientation = PageOrientation.Landscape;
        page.Size = PageSize.Letter;

        using var gfx = XGraphics.FromPdfPage(page);
        double pageW = page.Width.Point;
        double pageH = page.Height.Point;

        // ---- Header (title + date) ----
        var titleFont = new XFont("Arial", 12, XFontStyleEx.Bold);
        var subFont   = new XFont("Arial", 9);
        var footerFont= new XFont("Arial", 8);

        gfx.DrawString(modelTitle, titleFont, XBrushes.Black,
            new XRect(MarginPt, MarginPt, pageW - 2 * MarginPt, HeaderPt),
            XStringFormats.TopLeft);

        var stamp = $"Exported {DateTime.Now:yyyy-MM-dd HH:mm}";
        gfx.DrawString(stamp, subFont, XBrushes.Gray,
            new XRect(MarginPt, MarginPt, pageW - 2 * MarginPt, HeaderPt),
            XStringFormats.TopRight);

        // ---- Image area ----
        using var ms = new MemoryStream(pngBytes, writable: false);
        var img = XImage.FromStream(ms);

        double areaX = MarginPt;
        double areaY = MarginPt + HeaderPt;
        double areaW = pageW - 2 * MarginPt;
        double areaH = pageH - MarginPt - HeaderPt - MarginPt - FooterPt;

        double imgAspect  = (double)img.PixelWidth / img.PixelHeight;
        double areaAspect = areaW / areaH;
        double drawW, drawH;
        if (imgAspect > areaAspect) { drawW = areaW; drawH = areaW / imgAspect; }
        else                        { drawH = areaH; drawW = areaH * imgAspect; }
        double drawX = areaX + (areaW - drawW) / 2;
        double drawY = areaY + (areaH - drawH) / 2;

        gfx.DrawImage(img, drawX, drawY, drawW, drawH);

        // ---- Footer ----
        var footer = $"Image: {img.PixelWidth}×{img.PixelHeight} px  ·  Page: US Letter landscape  ·  Generated by NwdViewer";
        gfx.DrawString(footer, footerFont, XBrushes.Gray,
            new XRect(MarginPt, pageH - MarginPt - FooterPt, pageW - 2 * MarginPt, FooterPt),
            XStringFormats.BottomCenter);

        pdf.Save(path);
    }
}
